version: '3'

services:
  web:
    image: my_food_backend:0.0.1
    build: .
    command: ./runserver
    volumes:
      - ".:/my_food_backend"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:10.3
