# Generated by Django 2.2.4 on 2019-08-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190825_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measure',
            field=models.CharField(blank=True, choices=[('spoon', 'Colher'), ('cup', 'Xícara'), ('full', 'Inteiro')], max_length=10, null=True, verbose_name='Medida'),
        ),
    ]
